### ISSUE TITLE
Composer install didn't work

### ISSUE THREAD

**Issue by marcelthole** [captainhookphp/captainhook-phar#1]
Hey,

the first installation of the package results in an Exception, because the Builder.php (https://github.com/captainhookphp/captainhook/blob/main/src/Hook/Template/Builder.php#L55) requires the Bootstrap file `vendor/autoload.php` which does not exists for the first time.

```
Run '/projects/dummy/vendor/bin/captainhook install' to activate your hook configuration
  - Install hooks: 
In Builder.php line 51:
                                                                                                  
  bootstrap file not found: '/projects/dummy/vendor/autoload.php'  

```

## How to reproduce
1. Create a composer.json file
```json
{
  "require": {
    "captainhook/captainhook-phar": "5.7.0"
  }
}
```
2. run `composer install` (Composer version 2.0.12)

**Possible solution**
1. a fix could be to run the [install() Method](https://github.com/captainhookphp/captainhook-phar/blob/main/src/Plugin.php#L133 ) in the `POST_AUTOLOAD_DUMP` hook, but only if the `installHooks` was previously called.
2. fix this in the main repo of captainhook Builder.php

for the first version i could add a merge request with the changes

**Comment by marcelthole** [comment]
but it's there after the hook. Only the `vendor/autoload.php` file is missing. After the full `composer install` command the autoload.php is there and the install script works fine with the different templates

**Comment by sebastianfeldmann** [comment]
You are right, I like option 1. Do you want to provide the pull request?
