### ISSUE TITLE
Fatal Error In Bitbucket Pipelines

### ISSUE THREAD

**Issue by sprankhub** [captainhookphp/captainhook-phar#3]
We just migrated from `captainhook/captainhook` to `captainhook/captainhook-phar`. Unfortunately, this leads to an issue for us during `composer install` in Bitbucket Pipelines:

    [...]
    CaptainHook
     disabling plugin due to CI-environment
    CaptainHook
     disabling plugin due to CI-environment
    CaptainHook
     disabling plugin due to CI-environment
    Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
    Package laminas/laminas-console is abandoned, you should avoid using it. Use laminas/laminas-cli instead.
    Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
    Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
    Generating autoload files
      - Install hooks: 
    Fatal error: Uncaught TypeError: Argument 1 passed to CaptainHook\Composer\Captain::__construct() must be of the type string, null given, called in /opt/atlassian/pipelines/agent/build/vendor/captainhook/captainhook-phar/src/Plugin.php on line 142 and defined in /opt/atlassian/pipelines/agent/build/vendor/captainhook/captainhook-phar/src/Captain.php:50
    Stack trace:
    #0 /opt/atlassian/pipelines/agent/build/vendor/captainhook/captainhook-phar/src/Plugin.php(142): CaptainHook\Composer\Captain->__construct(NULL, NULL, NULL)
    #1 [internal function]: CaptainHook\Composer\Plugin->installHooksAfterPackageUpdate(Object(Composer\Script\Event))
    #2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(190): call_user_func(Array, Object(Composer\Script\Event))
    #3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(117): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
    #4 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(402) in /opt/atlassian/pipelines/agent/build/vendor/captainhook/captainhook-phar/src/Captain.php on line 50

What looks weird to me is that even though CaptainHook says it disabled the plugin due to the CI-environment, it still leads to an error.

Any idea, @sebastianfeldmann? Thanks!

**Comment by sebastianfeldmann** [comment]
I moved the CI check to the right position.

Please try the updated version. You might have to uninstall the package and reinstall it.

**Comment by sprankhub** [comment]
Thanks, @sebastianfeldmann! Now I get another interesting issue... When I execute `./vendor/bin/captainhook hook:pre-commit`, among others, `composer validate` is executed. This fails with another fatal error (this time, not in CI, but locally):

    Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Process\str_contains() in /var/www/html/vendor/symfony/process/Process.php:1401
    Stack trace:
    #0 /var/www/html/vendor/symfony/process/Process.php(328): Symfony\Component\Process\Process->isSigchildEnabled()
    #1 /var/www/html/vendor/symfony/process/Process.php(249): Symfony\Component\Process\Process->start(NULL, Array)
    #2 /var/www/html/vendor/sebastianfeldmann/cli/src/Processor/Symfony.php(46): Symfony\Component\Process\Process->run()
    #3 /var/www/html/vendor/captainhook/captainhook/src/Runner/Action/Cli.php(56): SebastianFeldmann\Cli\Processor\Symfony->run('composer valida...')
    #4 /var/www/html/vendor/captainhook/captainhook/src/Runner/Hook.php(344): CaptainHook\App\Runner\Action\Cli->execute(Object(CaptainHook\App\Config), Object(CaptainHook\App\Console\IO\DefaultIO), Object(SebastianFeldmann\Git\Repository), Object(CaptainHook\App\Config\Action))
    #5 /var/www/html/vendor/captainhook/captainhook/src/Runner/Hook.php(311): CaptainHook\App\Runner\Hook->ex in /var/www/html/vendor/symfony/process/Process.php on line 1401

I am still on PHP 7.4. Symfony seems to use `str_contains` from PHP 8, for which they have a polyfill. However, the polyfill does not seem to work in this case...

**Comment by sebastianfeldmann** [comment]
That's strange this should not happen anymore since I'm using the Symfony version 3 packages for the PHAR file and they do not need the polyfill or even have em. Are you sure you are using the latest version?
In doubt, just uninstall the `captainhook-phar` package and reinstall it with

    composer require captainhook/captainhook-phar

If you indeed have the latest version I have to investigate this further

**Comment by sprankhub** [comment]
I ran:

    composer remove --dev captainhook/captainhook-phar captainhook/plugin-composer --no-update
    composer update captainhook/captainhook-phar captainhook/plugin-composer --with-dependencies
    composer require --dev captainhook/captainhook-phar captainhook/plugin-composer --update-with-dependencies

I think this should then be the latest version of `captainhook/captainhook-phar`:

    $ composer show captainhook/captainhook-phar
    name     : captainhook/captainhook-phar
    descrip. : PHP git hook manager
    keywords : commit-msg, git, hooks, post-merge, pre-commit, pre-push, prepare-commit-msg
    versions : * 5.10.1
    type     : composer-plugin
    license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
    homepage : https://github.com/captainhookphp/captainhook
    source   : [git] https://github.com/captainhookphp/captainhook-phar.git 5c8bca70da93ccfa9f30b1514dd123c2201c0bcc
    dist     : [zip] https://api.github.com/repos/captainhookphp/captainhook-phar/zipball/5c8bca70da93ccfa9f30b1514dd123c2201c0bcc 5c8bca70da93ccfa9f30b1514dd123c2201c0bcc
    path     : /var/www/html/vendor/captainhook/captainhook-phar
    names    : captainhook/captainhook-phar

    support
    issues : https://github.com/captainhookphp/captainhook/issues
    source : https://github.com/captainhookphp/captainhook-phar/tree/5.10.1

    autoload
    psr-4
    CaptainHook\Composer\ => src/

    requires
    composer-plugin-api ^1.1||^2.0
    ext-json *
    ext-spl *
    phar-io/composer-distributor ^1.0
    php ^7.3 || ~8.0.0

    requires (dev)
    composer/composer ^1.1 || ^2.0

And `captainhook/plugin-composer`:

    $ composer show  captainhook/plugin-composer
    name     : captainhook/plugin-composer
    descrip. : Composer-Plugin handling your git-hooks
    keywords : 
    versions : * 5.3.1
    type     : composer-plugin
    license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
    homepage : 
    source   : [git] https://github.com/captainhookphp/plugin-composer.git 56e889e4a40628a77cc78306b6b05de173fd0284
    dist     : [zip] https://api.github.com/repos/captainhookphp/plugin-composer/zipball/56e889e4a40628a77cc78306b6b05de173fd0284 56e889e4a40628a77cc78306b6b05de173fd0284
    path     : /var/www/html/vendor/captainhook/plugin-composer
    names    : captainhook/plugin-composer

    support
    issues : https://github.com/captainhookphp/plugin-composer/issues
    source : https://github.com/captainhookphp/plugin-composer/tree/5.3.1

    autoload
    psr-4
    CaptainHook\Plugin\Composer\ => src

    requires
    captainhook/captainhook ^5.0
    composer-plugin-api ^1.1|^2.0
    php >=7.1

    requires (dev)
    composer/composer *

Still, I get the issue mentioned above. Based on the callstack, it looks like the `symonfy/process` package from the `vendor` directory is used (which is version `4.4.27`), not the one from your PHAR.

Could it be an issue that we use `captainhook/plugin-composer` together with the PHAR? Looks like `captainhook/plugin-composer` requires `captainhook/captainhook`, so that not only the PHAR version, but also the source version `captainhook/captainhook` is installed.

**Comment by sebastianfeldmann** [comment]
This is weird because this path `/var/www/html/vendor/symfony/process/Process.php` especially the `/var/www...` path looks strange.

This looks like a composer installed variant not the PHAR file.
Within the PHAR file all external classes are scoped, meaning `Symfony\Process` should be `CaptainHook\Ext\Symfony\Process`.

Please make sure you are really using the right captainhook executable or maybe your hooks are still referencing the old version.

**Comment by sprankhub** [comment]
I fully agree. However, I can reproduce the issue with the following minimal project:

`composer.json`

    {
        "name": "vendor/namespace",
        "authors": [
            {
                "name": "Firstname Lastname",
                "email": "name@tld"
            }
        ],
        "require": {
            "symfony/process": "~4.4"
        },
        "require-dev": {
            "captainhook/captainhook-phar": "^5.10",
            "captainhook/plugin-composer": "^5.3"
        }
    }

`captainhook.json`

    {
        "commit-msg": {
            "enabled": true,
            "actions": [
                {
                    "action": "\\CaptainHook\\App\\Hook\\Message\\Action\\Beams",
                    "options": {
                        "subjectLength": 50,
                        "bodyLineLength": 72
                    },
                    "conditions": []
                }
            ]
        },
        "pre-push": {
            "enabled": false,
            "actions": []
        },
        "pre-commit": {
            "enabled": true,
            "actions": [
                {
                    "action": "\\CaptainHook\\App\\Hook\\PHP\\Action\\Linting",
                    "options": [],
                    "conditions": []
                },
                {
                    "action": "composer validate",
                    "options": [],
                    "conditions": []
                }
            ]
        },
        "prepare-commit-msg": {
            "enabled": false,
            "actions": []
        },
        "post-commit": {
            "enabled": false,
            "actions": []
        },
        "post-merge": {
            "enabled": false,
            "actions": []
        },
        "post-checkout": {
            "enabled": false,
            "actions": []
        },
        "post-rewrite": {
            "enabled": false,
            "actions": []
        },
        "post-change": {
            "enabled": false,
            "actions": []
        }
    }

Then run:

1. `composer update`
2. `vendor/bin/captainhook install -f`
3. `vendor/bin/captainhook hook:pre-commit`

You should get the same error.

**Comment by sebastianfeldmann** [comment]
Just remove the `captainhook/plugin-composer` that's not needed anymore.
The `captainhook-phar` package is a plugin on its own.
I think then you should be fine.

**Comment by sprankhub** [comment]
So the PHAR will also automatically install the hooks on certain composer actions? Then we can indeed remove the other package.

Thanks!

**Comment by sprankhub** [comment]
Looking at the plugin code, it seems to install the hooks automatically:

https://github.com/captainhookphp/captainhook-phar/blob/3477b739cde897e19544586241e4eeb3e34be975/src/Plugin.php#L106-L129

The error is indeed gone since removing `captainhook/plugin-composer`. Thanks @sebastianfeldmann!
