### ISSUE TITLE
An error after running `hook:pre-commit` hook

### ISSUE THREAD

**Issue by iranimij** [captainhookphp/captainhook-phar#6]
I just tried to run `hook:pre-commit`, but I keep getting this below error: 

`failed PHP Error:Class "\SebastianFeldmann\Git\Operator\Index" not found in phar:///home/iman/Sites/test/vendor/bin/captainhook/vendor/sebastianfeldmann/git/src/Repository.php line 209
`

**How to reproduce:**
```
mkdit test && cd test
composer init
git init
composer require --dev captainhook/captainhook-phar
vendor/bin/captainhook hook:pre-commit
```

**Comment by sebastianfeldmann** [comment]
Should be fixed in `5.18.1`

Please let me know if it works for you as well.

**Comment by iranimij** [comment]
@sebastianfeldmann Yes, It's fixed, thanks

**Comment by sebastianfeldmann** [comment]
Thanks for letting me know :)
