### ISSUE TITLE
Failing composer platform check in version 5.23.4 and higher

### ISSUE THREAD

**Issue by norgeindian** [captainhookphp/captainhook-phar#7]
As soon as I install `captainhook/captainhook-phar` in version `5.23.4` or `5.23.5` and run `vendor/bin/captainhook -f install`, I get the following error:

> Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.30. in phar:///var/www/html/vendor/bin/captainhook/vendor/composer/platform_check.php on line 24

We are running a project inside docker, the mentioned PHP version 8.1.30 is correct, but I don't see any dependency in the whole project on PHP 8.2.
As soon as I downgrade to `5.23.3`, the error is gone and the configuration is properly set up.
Any idea, what might be wrong here?

**Comment by sebastianfeldmann** [comment]
I think the PHAR builder `Box` requires a minimum version of `8.2`. I will check if it can be manipulated somehow to run under some older PHP versions.

**Comment by sebastianfeldmann** [comment]
I just released `5.23.6` build on php 8.0 with an older `Box` version.
Please check if that works for you again.

**Comment by norgeindian** [comment]
@sebastianfeldmann , unfortunately, it does not.
The installation command now works, but as soon as the first hook runs, I get the following error:

```
Box Requirements Checker
========================
> Using PHP 8.3.6
> PHP is using the following php.ini file:
  /etc/php/8.3/cli/php.ini
> Checking Box requirements:
  ....E.E
 [ERROR] Your system is not ready to run the application.                       
Fix the following mandatory requirements:
=========================================
 * The application requires the extension "xml". Enable it or install a
   polyfill.
 * The package "sebastianfeldmann/git" requires the extension "simplexml".
   Enable it or install a polyfill.
```

**Comment by norgeindian** [comment]
Strangely it now fails as well, when I use `5.23.3`, at least in a new project.

**Comment by sebastianfeldmann** [comment]
New php setup?

Looks like you are missing some `php-extensions`  like `xml` and `simplexml`.

Please check your php info if you have the necessary extensions enabled.
Maybe your CLI php.ini does not include them.

**Comment by norgeindian** [comment]
Ah, interesting, found the issue.
It is related to https://github.com/captainhookphp/captainhook/issues/261.
This one here can actually be closed, this is indeed fixed with your new update.
Let me share details in the correct issue description.
Thanks as always for your amazingly fast help.
